export const GRAPHWEAVER_CORE_TARGET_VERSION = '0.1.0-alpha.0';
export const GRAPHWEAVER_REST_TARGET_VERSION = '0.1.0-alpha.0';
export const GRAPHWEAVER_MIKROORM_TARGET_VERSION = '0.1.0-alpha.1';
export const GRAPHWEAVER_APOLLO_TARGET_VERSION = '0.1.0-alpha.1';
export const MIKRO_ORM_TARGET_VERSION = '5.4.2';
