version: "3.9"
services:
  graphweaver-dev:
    container_name: graphweaver-dev 
    build: .
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ..:/app
    tty: true

  db:
    container_name: graphweaver-dev-db
    image: "postgres:14"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: "graphweaver"
      POSTGRES_USER: "graphweaver"
      POSTGRES_PASSWORD: "graphweaver"
