/* eslint-disable */
/* 
* This file is auto-generated by Graphweaver. 
* Please do not edit it directly.
*/
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** Image type scalar */
  Image: { input: any; output: any; }
  /** The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf). */
  JSON: { input: any; output: any; }
};

export type AdminUiEntityAttributeMetadata = {
  __typename?: 'AdminUiEntityAttributeMetadata';
  exportPageSize?: Maybe<Scalars['Float']['output']>;
  isReadOnly?: Maybe<Scalars['Boolean']['output']>;
};

export type AdminUiEntityMetadata = {
  __typename?: 'AdminUiEntityMetadata';
  attributes: AdminUiEntityAttributeMetadata;
  backendId?: Maybe<Scalars['String']['output']>;
  defaultFilter?: Maybe<Scalars['JSON']['output']>;
  fields: Array<AdminUiFieldMetadata>;
  name: Scalars['String']['output'];
  plural: Scalars['String']['output'];
  summaryField?: Maybe<Scalars['String']['output']>;
};

export type AdminUiEnumMetadata = {
  __typename?: 'AdminUiEnumMetadata';
  name: Scalars['String']['output'];
  values: Array<AdminUiEnumValueMetadata>;
};

export type AdminUiEnumValueMetadata = {
  __typename?: 'AdminUiEnumValueMetadata';
  name: Scalars['String']['output'];
  value: Scalars['String']['output'];
};

export type AdminUiFieldAttributeMetadata = {
  __typename?: 'AdminUiFieldAttributeMetadata';
  isReadOnly: Scalars['Boolean']['output'];
  isRequired: Scalars['Boolean']['output'];
};

export type AdminUiFieldExtensionsMetadata = {
  __typename?: 'AdminUiFieldExtensionsMetadata';
  key?: Maybe<Scalars['String']['output']>;
};

export type AdminUiFieldMetadata = {
  __typename?: 'AdminUiFieldMetadata';
  attributes?: Maybe<AdminUiFieldAttributeMetadata>;
  extensions?: Maybe<AdminUiFieldExtensionsMetadata>;
  filter?: Maybe<AdminUiFilterMetadata>;
  isArray?: Maybe<Scalars['Boolean']['output']>;
  name: Scalars['String']['output'];
  relatedEntity?: Maybe<Scalars['String']['output']>;
  relationshipType?: Maybe<Scalars['String']['output']>;
  type: Scalars['String']['output'];
};

export type AdminUiFilterMetadata = {
  __typename?: 'AdminUiFilterMetadata';
  type: AdminUiFilterType;
};

export enum AdminUiFilterType {
  Boolean = 'BOOLEAN',
  DateRange = 'DATE_RANGE',
  Enum = 'ENUM',
  Numeric = 'NUMERIC',
  Relationship = 'RELATIONSHIP',
  Text = 'TEXT'
}

export type AdminUiMetadata = {
  __typename?: 'AdminUiMetadata';
  entities: Array<AdminUiEntityMetadata>;
  enums: Array<AdminUiEnumMetadata>;
};

export type DeleteOneFilterInput = {
  id: Scalars['ID']['input'];
};

export type Function = {
  __typename?: 'Function';
  downloadUrl: Scalars['Image']['output'];
};

/** Data needed to create or update UnknownTypePlural. If an ID is passed, this is an update, otherwise it's an insert. */
export type FunctionCreateOrUpdateInput = {
  downloadUrl?: InputMaybe<Scalars['Image']['input']>;
};

/** Data needed to create UnknownTypePlural. */
export type FunctionInsertInput = {
  downloadUrl: Scalars['Image']['input'];
};

/** Data needed to update UnknownTypePlural. An ID must be passed. */
export type FunctionUpdateInput = {
  downloadUrl?: InputMaybe<Scalars['Image']['input']>;
};

export type Mutation = {
  __typename?: 'Mutation';
  /** Create a single Function. */
  createFunction?: Maybe<Function>;
  /** Create or update many Submissions. */
  createOrUpdateSubmissions?: Maybe<Array<Maybe<Submission>>>;
  /** Create or update many UnknownTypePlural. */
  createOrUpdateUnknownTypePlural?: Maybe<Array<Maybe<Function>>>;
  /** Create a single Submission. */
  createSubmission?: Maybe<Submission>;
  /** Create many Submissions. */
  createSubmissions?: Maybe<Array<Maybe<Submission>>>;
  /** Create many UnknownTypePlural. */
  createUnknownTypePlural?: Maybe<Array<Maybe<Function>>>;
  /** Delete a single Function. */
  deleteFunction?: Maybe<Scalars['Boolean']['output']>;
  /** Delete a single Submission. */
  deleteSubmission?: Maybe<Scalars['Boolean']['output']>;
  /** Delete many Submissions with a filter. */
  deleteSubmissions?: Maybe<Scalars['Boolean']['output']>;
  /** Delete many UnknownTypePlural with a filter. */
  deleteUnknownTypePlural?: Maybe<Scalars['Boolean']['output']>;
  /** Update a single Function. */
  updateFunction?: Maybe<Function>;
  /** Update a single Submission. */
  updateSubmission?: Maybe<Submission>;
  /** Update many Submissions. */
  updateSubmissions?: Maybe<Array<Maybe<Submission>>>;
  /** Update many UnknownTypePlural. */
  updateUnknownTypePlural?: Maybe<Array<Maybe<Function>>>;
};


export type MutationCreateFunctionArgs = {
  input: FunctionInsertInput;
};


export type MutationCreateOrUpdateSubmissionsArgs = {
  input: Array<SubmissionCreateOrUpdateInput>;
};


export type MutationCreateOrUpdateUnknownTypePluralArgs = {
  input: Array<FunctionCreateOrUpdateInput>;
};


export type MutationCreateSubmissionArgs = {
  input: SubmissionInsertInput;
};


export type MutationCreateSubmissionsArgs = {
  input: Array<SubmissionInsertInput>;
};


export type MutationCreateUnknownTypePluralArgs = {
  input: Array<FunctionInsertInput>;
};


export type MutationDeleteFunctionArgs = {
  filter: DeleteOneFilterInput;
};


export type MutationDeleteSubmissionArgs = {
  filter: DeleteOneFilterInput;
};


export type MutationDeleteSubmissionsArgs = {
  filter: SubmissionsListFilter;
};


export type MutationDeleteUnknownTypePluralArgs = {
  filter: UnknownTypePluralListFilter;
};


export type MutationUpdateFunctionArgs = {
  input: FunctionUpdateInput;
};


export type MutationUpdateSubmissionArgs = {
  input: SubmissionUpdateInput;
};


export type MutationUpdateSubmissionsArgs = {
  input: Array<SubmissionUpdateInput>;
};


export type MutationUpdateUnknownTypePluralArgs = {
  input: Array<FunctionUpdateInput>;
};

export type Query = {
  __typename?: 'Query';
  /** Query used by the Admin UI to introspect the schema and metadata. */
  _graphweaver?: Maybe<AdminUiMetadata>;
  /** Get a single Function. */
  function?: Maybe<Function>;
  getDownloadUrl?: Maybe<Scalars['String']['output']>;
  getUploadUrl?: Maybe<Scalars['String']['output']>;
  /** Get a single Submission. */
  submission?: Maybe<Submission>;
  /** Get multiple Submissions. */
  submissions?: Maybe<Array<Maybe<Submission>>>;
  /** Get multiple UnknownTypePlural. */
  unknownTypePlural?: Maybe<Array<Maybe<Function>>>;
};


export type QueryFunctionArgs = {
  id: Scalars['ID']['input'];
};


export type QueryGetDownloadUrlArgs = {
  key?: InputMaybe<Scalars['ID']['input']>;
};


export type QueryGetUploadUrlArgs = {
  key?: InputMaybe<Scalars['ID']['input']>;
};


export type QuerySubmissionArgs = {
  id: Scalars['ID']['input'];
};


export type QuerySubmissionsArgs = {
  filter?: InputMaybe<SubmissionsListFilter>;
  pagination?: InputMaybe<SubmissionsPaginationInput>;
};


export type QueryUnknownTypePluralArgs = {
  filter?: InputMaybe<UnknownTypePluralListFilter>;
};

export enum Sort {
  Asc = 'ASC',
  Desc = 'DESC'
}

export type Submission = {
  __typename?: 'Submission';
  id: Scalars['ID']['output'];
  key?: Maybe<Scalars['String']['output']>;
};

/** Data needed to create or update Submissions. If an ID is passed, this is an update, otherwise it's an insert. */
export type SubmissionCreateOrUpdateInput = {
  id?: InputMaybe<Scalars['ID']['input']>;
  key?: InputMaybe<Scalars['String']['input']>;
};

/** Data needed to create Submissions. */
export type SubmissionInsertInput = {
  key?: InputMaybe<Scalars['String']['input']>;
};

/** Data needed to update Submissions. An ID must be passed. */
export type SubmissionUpdateInput = {
  id: Scalars['ID']['input'];
  key?: InputMaybe<Scalars['String']['input']>;
};

export type SubmissionsListFilter = {
  id?: InputMaybe<Scalars['ID']['input']>;
  id_in?: InputMaybe<Array<Scalars['ID']['input']>>;
  id_ne?: InputMaybe<Scalars['ID']['input']>;
  id_nin?: InputMaybe<Array<Scalars['ID']['input']>>;
  id_notnull?: InputMaybe<Scalars['Boolean']['input']>;
  id_null?: InputMaybe<Scalars['Boolean']['input']>;
  key?: InputMaybe<Scalars['String']['input']>;
  key_ilike?: InputMaybe<Scalars['String']['input']>;
  key_in?: InputMaybe<Array<Scalars['String']['input']>>;
  key_like?: InputMaybe<Scalars['String']['input']>;
  key_ne?: InputMaybe<Scalars['String']['input']>;
  key_nin?: InputMaybe<Array<Scalars['String']['input']>>;
  key_notnull?: InputMaybe<Scalars['Boolean']['input']>;
  key_null?: InputMaybe<Scalars['Boolean']['input']>;
};

export type SubmissionsOrderByInput = {
  id?: InputMaybe<Sort>;
  key?: InputMaybe<Sort>;
};

/** Pagination options for Submissions. */
export type SubmissionsPaginationInput = {
  limit?: InputMaybe<Scalars['Int']['input']>;
  offset?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<SubmissionsOrderByInput>;
};

export type UnknownTypePluralListFilter = {
  downloadUrl?: InputMaybe<Scalars['Image']['input']>;
  downloadUrl_in?: InputMaybe<Array<Scalars['Image']['input']>>;
  downloadUrl_ne?: InputMaybe<Scalars['Image']['input']>;
  downloadUrl_nin?: InputMaybe<Array<Scalars['Image']['input']>>;
  downloadUrl_notnull?: InputMaybe<Scalars['Boolean']['input']>;
  downloadUrl_null?: InputMaybe<Scalars['Boolean']['input']>;
};
