/**
 * The PostgreSQL form of the shared conformance schema.
 *
 * `GENERATED BY DEFAULT AS IDENTITY` rather than `ALWAYS`, because the seed inserts explicit ids.
 * That leaves the sequence behind the seeded rows, which is what `afterSeed` corrects.
 */
export const ddl = [
	`CREATE TABLE artist (
		artist_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT NOT NULL
	)`,
	`CREATE TABLE album (
		album_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		title TEXT NOT NULL,
		artist_id INT REFERENCES artist(artist_id)
	)`,
	`CREATE TABLE track (
		track_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT NOT NULL,
		album_id INT REFERENCES album(album_id),
		milliseconds INT
	)`,
	`CREATE TABLE genre (
		genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT NOT NULL
	)`,
	`CREATE TABLE track_genre (
		track_id INT NOT NULL REFERENCES track(track_id),
		genre_id INT NOT NULL REFERENCES genre(genre_id),
		PRIMARY KEY (track_id, genre_id)
	)`,
	`CREATE TABLE app_user (
		id TEXT PRIMARY KEY,
		username TEXT NOT NULL,
		password_hash TEXT NOT NULL,
		tenant_id TEXT NOT NULL,
		roles TEXT,
		preferences JSONB
	)`,
];

/** Move each identity sequence past the explicit ids the seed inserted. */
export const afterSeed = ['artist', 'album', 'track', 'genre'].map(
	(table) =>
		`SELECT setval(pg_get_serial_sequence('${table}', '${table}_id'), (SELECT MAX(${table}_id) FROM ${table}))`
);
