/* eslint-disable */
/* 
* This file is auto-generated by Graphweaver. 
* Please do not edit it directly.
*/
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** Returns a string in simplified extended ISO format (ISO 8601), which is always 24 or 27 characters long (YYYY-MM-DDTHH:mm:ss.sssZ or ±YYYYYY-MM-DDTHH:mm:ss.sssZ, respectively). The timezone is always zero UTC offset, as denoted by the suffix "Z". */
  ISOString: { input: any; output: any; }
};

export type Query = {
  __typename?: 'Query';
  tenants: Array<Tenant>;
  tenant?: Maybe<Tenant>;
  accounts: Array<Account>;
  account?: Maybe<Account>;
  profitAndLossRows: Array<ProfitAndLossRow>;
  profitAndLossRow?: Maybe<ProfitAndLossRow>;
  _graphweaver: AdminUiMetadata;
};


export type QueryTenantsArgs = {
  pagination?: InputMaybe<TenantsPaginationInput>;
  filter?: InputMaybe<TenantsListFilter>;
};


export type QueryTenantArgs = {
  id: Scalars['ID']['input'];
};


export type QueryAccountsArgs = {
  pagination?: InputMaybe<AccountsPaginationInput>;
  filter?: InputMaybe<AccountsListFilter>;
};


export type QueryAccountArgs = {
  id: Scalars['ID']['input'];
};


export type QueryProfitAndLossRowsArgs = {
  pagination?: InputMaybe<ProfitAndLossRowsPaginationInput>;
  filter?: InputMaybe<ProfitAndLossRowsListFilter>;
};


export type QueryProfitAndLossRowArgs = {
  id: Scalars['ID']['input'];
};

export type Tenant = {
  __typename?: 'Tenant';
  id: Scalars['ID']['output'];
  authEventId: Scalars['String']['output'];
  tenantName: Scalars['String']['output'];
  tenantType: Scalars['String']['output'];
  createdDateUtc: Scalars['String']['output'];
  updatedDateUtc: Scalars['String']['output'];
};

export type TenantsPaginationInput = {
  limit?: InputMaybe<Scalars['Int']['input']>;
  offset?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<TenantsOrderByInput>;
};

export type TenantsOrderByInput = {
  id?: InputMaybe<Sort>;
  authEventId?: InputMaybe<Sort>;
  tenantName?: InputMaybe<Sort>;
  tenantType?: InputMaybe<Sort>;
  createdDateUtc?: InputMaybe<Sort>;
  updatedDateUtc?: InputMaybe<Sort>;
};

export enum Sort {
  Asc = 'ASC',
  Desc = 'DESC'
}

export type TenantsListFilter = {
  _and?: InputMaybe<Array<TenantsListFilter>>;
  _or?: InputMaybe<Array<TenantsListFilter>>;
  _not?: InputMaybe<TenantsListFilter>;
  id?: InputMaybe<Scalars['ID']['input']>;
  id_ne?: InputMaybe<Scalars['ID']['input']>;
  id_in?: InputMaybe<Array<Scalars['ID']['input']>>;
  id_nin?: InputMaybe<Array<Scalars['ID']['input']>>;
  id_notnull?: InputMaybe<Scalars['ID']['input']>;
  id_null?: InputMaybe<Scalars['ID']['input']>;
  authEventId?: InputMaybe<Scalars['String']['input']>;
  authEventId_ne?: InputMaybe<Scalars['String']['input']>;
  authEventId_in?: InputMaybe<Array<Scalars['String']['input']>>;
  authEventId_nin?: InputMaybe<Array<Scalars['String']['input']>>;
  authEventId_like?: InputMaybe<Scalars['String']['input']>;
  authEventId_ilike?: InputMaybe<Scalars['String']['input']>;
  authEventId_notnull?: InputMaybe<Scalars['String']['input']>;
  authEventId_null?: InputMaybe<Scalars['String']['input']>;
  tenantName?: InputMaybe<Scalars['String']['input']>;
  tenantName_ne?: InputMaybe<Scalars['String']['input']>;
  tenantName_in?: InputMaybe<Array<Scalars['String']['input']>>;
  tenantName_nin?: InputMaybe<Array<Scalars['String']['input']>>;
  tenantName_like?: InputMaybe<Scalars['String']['input']>;
  tenantName_ilike?: InputMaybe<Scalars['String']['input']>;
  tenantName_notnull?: InputMaybe<Scalars['String']['input']>;
  tenantName_null?: InputMaybe<Scalars['String']['input']>;
  tenantType?: InputMaybe<Scalars['String']['input']>;
  tenantType_ne?: InputMaybe<Scalars['String']['input']>;
  tenantType_in?: InputMaybe<Array<Scalars['String']['input']>>;
  tenantType_nin?: InputMaybe<Array<Scalars['String']['input']>>;
  tenantType_like?: InputMaybe<Scalars['String']['input']>;
  tenantType_ilike?: InputMaybe<Scalars['String']['input']>;
  tenantType_notnull?: InputMaybe<Scalars['String']['input']>;
  tenantType_null?: InputMaybe<Scalars['String']['input']>;
  createdDateUtc?: InputMaybe<Scalars['String']['input']>;
  createdDateUtc_ne?: InputMaybe<Scalars['String']['input']>;
  createdDateUtc_in?: InputMaybe<Array<Scalars['String']['input']>>;
  createdDateUtc_nin?: InputMaybe<Array<Scalars['String']['input']>>;
  createdDateUtc_like?: InputMaybe<Scalars['String']['input']>;
  createdDateUtc_ilike?: InputMaybe<Scalars['String']['input']>;
  createdDateUtc_notnull?: InputMaybe<Scalars['String']['input']>;
  createdDateUtc_null?: InputMaybe<Scalars['String']['input']>;
  updatedDateUtc?: InputMaybe<Scalars['String']['input']>;
  updatedDateUtc_ne?: InputMaybe<Scalars['String']['input']>;
  updatedDateUtc_in?: InputMaybe<Array<Scalars['String']['input']>>;
  updatedDateUtc_nin?: InputMaybe<Array<Scalars['String']['input']>>;
  updatedDateUtc_like?: InputMaybe<Scalars['String']['input']>;
  updatedDateUtc_ilike?: InputMaybe<Scalars['String']['input']>;
  updatedDateUtc_notnull?: InputMaybe<Scalars['String']['input']>;
  updatedDateUtc_null?: InputMaybe<Scalars['String']['input']>;
};

export type Account = {
  __typename?: 'Account';
  id: Scalars['ID']['output'];
  code?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  type?: Maybe<AccountType>;
  tenantId: Scalars['String']['output'];
  tenant?: Maybe<Tenant>;
};

export enum AccountType {
  Bank = 'BANK',
  Current = 'CURRENT',
  Currliab = 'CURRLIAB',
  Depreciatn = 'DEPRECIATN',
  Directcosts = 'DIRECTCOSTS',
  Equity = 'EQUITY',
  Expense = 'EXPENSE',
  Fixed = 'FIXED',
  Inventory = 'INVENTORY',
  Liability = 'LIABILITY',
  Noncurrent = 'NONCURRENT',
  Otherincome = 'OTHERINCOME',
  Overheads = 'OVERHEADS',
  Prepayment = 'PREPAYMENT',
  Revenue = 'REVENUE',
  Sales = 'SALES',
  Termliab = 'TERMLIAB',
  Paygliability = 'PAYGLIABILITY',
  Payg = 'PAYG',
  Superannuationexpense = 'SUPERANNUATIONEXPENSE',
  Superannuationliability = 'SUPERANNUATIONLIABILITY',
  Wagesexpense = 'WAGESEXPENSE'
}

export type AccountsPaginationInput = {
  limit?: InputMaybe<Scalars['Int']['input']>;
  offset?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<AccountsOrderByInput>;
};

export type AccountsOrderByInput = {
  id?: InputMaybe<Sort>;
  code?: InputMaybe<Sort>;
  name?: InputMaybe<Sort>;
  type?: InputMaybe<Sort>;
  tenantId?: InputMaybe<Sort>;
};

export type AccountsListFilter = {
  _and?: InputMaybe<Array<AccountsListFilter>>;
  _or?: InputMaybe<Array<AccountsListFilter>>;
  _not?: InputMaybe<AccountsListFilter>;
  id?: InputMaybe<Scalars['ID']['input']>;
  id_ne?: InputMaybe<Scalars['ID']['input']>;
  id_in?: InputMaybe<Array<Scalars['ID']['input']>>;
  id_nin?: InputMaybe<Array<Scalars['ID']['input']>>;
  id_notnull?: InputMaybe<Scalars['ID']['input']>;
  id_null?: InputMaybe<Scalars['ID']['input']>;
  code?: InputMaybe<Scalars['String']['input']>;
  code_ne?: InputMaybe<Scalars['String']['input']>;
  code_in?: InputMaybe<Array<Scalars['String']['input']>>;
  code_nin?: InputMaybe<Array<Scalars['String']['input']>>;
  code_like?: InputMaybe<Scalars['String']['input']>;
  code_ilike?: InputMaybe<Scalars['String']['input']>;
  code_notnull?: InputMaybe<Scalars['String']['input']>;
  code_null?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  name_ne?: InputMaybe<Scalars['String']['input']>;
  name_in?: InputMaybe<Array<Scalars['String']['input']>>;
  name_nin?: InputMaybe<Array<Scalars['String']['input']>>;
  name_like?: InputMaybe<Scalars['String']['input']>;
  name_ilike?: InputMaybe<Scalars['String']['input']>;
  name_notnull?: InputMaybe<Scalars['String']['input']>;
  name_null?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<AccountType>;
  type_ne?: InputMaybe<AccountType>;
  type_in?: InputMaybe<Array<AccountType>>;
  type_nin?: InputMaybe<Array<AccountType>>;
  type_notnull?: InputMaybe<AccountType>;
  type_null?: InputMaybe<AccountType>;
  tenantId?: InputMaybe<Scalars['String']['input']>;
  tenantId_ne?: InputMaybe<Scalars['String']['input']>;
  tenantId_in?: InputMaybe<Array<Scalars['String']['input']>>;
  tenantId_nin?: InputMaybe<Array<Scalars['String']['input']>>;
  tenantId_like?: InputMaybe<Scalars['String']['input']>;
  tenantId_ilike?: InputMaybe<Scalars['String']['input']>;
  tenantId_notnull?: InputMaybe<Scalars['String']['input']>;
  tenantId_null?: InputMaybe<Scalars['String']['input']>;
  tenant?: InputMaybe<TenantsListFilter>;
};

export type ProfitAndLossRow = {
  __typename?: 'ProfitAndLossRow';
  id: Scalars['ID']['output'];
  date: Scalars['ISOString']['output'];
  description: Scalars['String']['output'];
  amount: Scalars['Float']['output'];
  accountId?: Maybe<Scalars['ID']['output']>;
  account?: Maybe<Account>;
  tenantId?: Maybe<Scalars['ID']['output']>;
  tenant?: Maybe<Tenant>;
};

export type ProfitAndLossRowsPaginationInput = {
  limit?: InputMaybe<Scalars['Int']['input']>;
  offset?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<ProfitAndLossRowsOrderByInput>;
};

export type ProfitAndLossRowsOrderByInput = {
  id?: InputMaybe<Sort>;
  date?: InputMaybe<Sort>;
  description?: InputMaybe<Sort>;
  amount?: InputMaybe<Sort>;
  accountId?: InputMaybe<Sort>;
  tenantId?: InputMaybe<Sort>;
};

export type ProfitAndLossRowsListFilter = {
  _and?: InputMaybe<Array<ProfitAndLossRowsListFilter>>;
  _or?: InputMaybe<Array<ProfitAndLossRowsListFilter>>;
  _not?: InputMaybe<ProfitAndLossRowsListFilter>;
  id?: InputMaybe<Scalars['ID']['input']>;
  id_ne?: InputMaybe<Scalars['ID']['input']>;
  id_in?: InputMaybe<Array<Scalars['ID']['input']>>;
  id_nin?: InputMaybe<Array<Scalars['ID']['input']>>;
  id_notnull?: InputMaybe<Scalars['ID']['input']>;
  id_null?: InputMaybe<Scalars['ID']['input']>;
  date?: InputMaybe<Scalars['ISOString']['input']>;
  date_gt?: InputMaybe<Scalars['ISOString']['input']>;
  date_gte?: InputMaybe<Scalars['ISOString']['input']>;
  date_lt?: InputMaybe<Scalars['ISOString']['input']>;
  date_lte?: InputMaybe<Scalars['ISOString']['input']>;
  date_ne?: InputMaybe<Scalars['ISOString']['input']>;
  date_in?: InputMaybe<Array<Scalars['ISOString']['input']>>;
  date_nin?: InputMaybe<Array<Scalars['ISOString']['input']>>;
  date_notnull?: InputMaybe<Scalars['ISOString']['input']>;
  date_null?: InputMaybe<Scalars['ISOString']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  description_ne?: InputMaybe<Scalars['String']['input']>;
  description_in?: InputMaybe<Array<Scalars['String']['input']>>;
  description_nin?: InputMaybe<Array<Scalars['String']['input']>>;
  description_like?: InputMaybe<Scalars['String']['input']>;
  description_ilike?: InputMaybe<Scalars['String']['input']>;
  description_notnull?: InputMaybe<Scalars['String']['input']>;
  description_null?: InputMaybe<Scalars['String']['input']>;
  amount?: InputMaybe<Scalars['Float']['input']>;
  amount_gt?: InputMaybe<Scalars['Float']['input']>;
  amount_gte?: InputMaybe<Scalars['Float']['input']>;
  amount_lt?: InputMaybe<Scalars['Float']['input']>;
  amount_lte?: InputMaybe<Scalars['Float']['input']>;
  amount_ne?: InputMaybe<Scalars['Float']['input']>;
  amount_in?: InputMaybe<Array<Scalars['Float']['input']>>;
  amount_nin?: InputMaybe<Array<Scalars['Float']['input']>>;
  amount_notnull?: InputMaybe<Scalars['Float']['input']>;
  amount_null?: InputMaybe<Scalars['Float']['input']>;
  accountId?: InputMaybe<Scalars['ID']['input']>;
  accountId_ne?: InputMaybe<Scalars['ID']['input']>;
  accountId_in?: InputMaybe<Array<Scalars['ID']['input']>>;
  accountId_nin?: InputMaybe<Array<Scalars['ID']['input']>>;
  accountId_notnull?: InputMaybe<Scalars['ID']['input']>;
  accountId_null?: InputMaybe<Scalars['ID']['input']>;
  account?: InputMaybe<AccountsListFilter>;
  tenantId?: InputMaybe<Scalars['ID']['input']>;
  tenantId_ne?: InputMaybe<Scalars['ID']['input']>;
  tenantId_in?: InputMaybe<Array<Scalars['ID']['input']>>;
  tenantId_nin?: InputMaybe<Array<Scalars['ID']['input']>>;
  tenantId_notnull?: InputMaybe<Scalars['ID']['input']>;
  tenantId_null?: InputMaybe<Scalars['ID']['input']>;
  tenant?: InputMaybe<TenantsListFilter>;
};

export type AdminUiMetadata = {
  __typename?: 'AdminUiMetadata';
  entities: Array<AdminUiEntityMetadata>;
  enums: Array<AdminUiEnumMetadata>;
};

export type AdminUiEntityMetadata = {
  __typename?: 'AdminUiEntityMetadata';
  name: Scalars['String']['output'];
  backendId?: Maybe<Scalars['String']['output']>;
  summaryField?: Maybe<Scalars['String']['output']>;
  fields: Array<AdminUiFieldMetadata>;
  attributes: AdminUiEntityAttributeMetadata;
};

export type AdminUiFieldMetadata = {
  __typename?: 'AdminUiFieldMetadata';
  name: Scalars['String']['output'];
  type: Scalars['String']['output'];
  relationshipType?: Maybe<Scalars['String']['output']>;
  relatedEntity?: Maybe<Scalars['String']['output']>;
  filter?: Maybe<AdminUiFilterMetadata>;
  attributes?: Maybe<AdminUiFieldAttributeMetadata>;
};

export type AdminUiFilterMetadata = {
  __typename?: 'AdminUiFilterMetadata';
  type: AdminUiFilterType;
};

export enum AdminUiFilterType {
  DateRange = 'DATE_RANGE',
  Enum = 'ENUM',
  Numeric = 'NUMERIC',
  Relationship = 'RELATIONSHIP',
  Text = 'TEXT',
  Boolean = 'BOOLEAN'
}

export type AdminUiFieldAttributeMetadata = {
  __typename?: 'AdminUiFieldAttributeMetadata';
  isReadOnly?: Maybe<Scalars['Boolean']['output']>;
};

export type AdminUiEntityAttributeMetadata = {
  __typename?: 'AdminUiEntityAttributeMetadata';
  isReadOnly?: Maybe<Scalars['Boolean']['output']>;
};

export type AdminUiEnumMetadata = {
  __typename?: 'AdminUiEnumMetadata';
  name: Scalars['String']['output'];
  values: Array<AdminUiEnumValueMetadata>;
};

export type AdminUiEnumValueMetadata = {
  __typename?: 'AdminUiEnumValueMetadata';
  name: Scalars['String']['output'];
  value: Scalars['String']['output'];
};

export type Mutation = {
  __typename?: 'Mutation';
  createTenants: Array<Tenant>;
  createTenant: Tenant;
  updateTenants: Array<Tenant>;
  createOrUpdateTenants: Array<Tenant>;
  updateTenant: Tenant;
  deleteTenant: Scalars['Boolean']['output'];
  createAccounts: Array<Account>;
  createAccount: Account;
  updateAccounts: Array<Account>;
  createOrUpdateAccounts: Array<Account>;
  updateAccount: Account;
  deleteAccount: Scalars['Boolean']['output'];
  createProfitAndLossRows: Array<ProfitAndLossRow>;
  createProfitAndLossRow: ProfitAndLossRow;
  updateProfitAndLossRows: Array<ProfitAndLossRow>;
  createOrUpdateProfitAndLossRows: Array<ProfitAndLossRow>;
  updateProfitAndLossRow: ProfitAndLossRow;
  deleteProfitAndLossRow: Scalars['Boolean']['output'];
};


export type MutationCreateTenantsArgs = {
  input: TenantsInsertManyInput;
};


export type MutationCreateTenantArgs = {
  data: TenantInsertInput;
};


export type MutationUpdateTenantsArgs = {
  input: TenantsUpdateManyInput;
};


export type MutationCreateOrUpdateTenantsArgs = {
  input: TenantsCreateOrUpdateManyInput;
};


export type MutationUpdateTenantArgs = {
  data: TenantCreateOrUpdateInput;
};


export type MutationDeleteTenantArgs = {
  id: Scalars['ID']['input'];
};


export type MutationCreateAccountsArgs = {
  input: AccountsInsertManyInput;
};


export type MutationCreateAccountArgs = {
  data: AccountInsertInput;
};


export type MutationUpdateAccountsArgs = {
  input: AccountsUpdateManyInput;
};


export type MutationCreateOrUpdateAccountsArgs = {
  input: AccountsCreateOrUpdateManyInput;
};


export type MutationUpdateAccountArgs = {
  data: AccountCreateOrUpdateInput;
};


export type MutationDeleteAccountArgs = {
  id: Scalars['ID']['input'];
};


export type MutationCreateProfitAndLossRowsArgs = {
  input: ProfitAndLossRowsInsertManyInput;
};


export type MutationCreateProfitAndLossRowArgs = {
  data: ProfitAndLossRowInsertInput;
};


export type MutationUpdateProfitAndLossRowsArgs = {
  input: ProfitAndLossRowsUpdateManyInput;
};


export type MutationCreateOrUpdateProfitAndLossRowsArgs = {
  input: ProfitAndLossRowsCreateOrUpdateManyInput;
};


export type MutationUpdateProfitAndLossRowArgs = {
  data: ProfitAndLossRowCreateOrUpdateInput;
};


export type MutationDeleteProfitAndLossRowArgs = {
  id: Scalars['ID']['input'];
};

export type TenantsInsertManyInput = {
  data: Array<TenantInsertInput>;
};

export type TenantInsertInput = {
  authEventId: Scalars['String']['input'];
  tenantName: Scalars['String']['input'];
  tenantType: Scalars['String']['input'];
  createdDateUtc: Scalars['String']['input'];
  updatedDateUtc: Scalars['String']['input'];
};

export type TenantsUpdateManyInput = {
  data: Array<TenantCreateOrUpdateInput>;
};

export type TenantCreateOrUpdateInput = {
  id?: InputMaybe<Scalars['ID']['input']>;
  authEventId?: InputMaybe<Scalars['String']['input']>;
  tenantName?: InputMaybe<Scalars['String']['input']>;
  tenantType?: InputMaybe<Scalars['String']['input']>;
  createdDateUtc?: InputMaybe<Scalars['String']['input']>;
  updatedDateUtc?: InputMaybe<Scalars['String']['input']>;
};

export type TenantsCreateOrUpdateManyInput = {
  data: Array<TenantCreateOrUpdateInput>;
};

export type AccountsInsertManyInput = {
  data: Array<AccountInsertInput>;
};

export type AccountInsertInput = {
  code?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<AccountType>;
  tenantId: Scalars['String']['input'];
  tenant?: InputMaybe<TenantCreateOrUpdateInput>;
};

export type AccountsUpdateManyInput = {
  data: Array<AccountCreateOrUpdateInput>;
};

export type AccountCreateOrUpdateInput = {
  id?: InputMaybe<Scalars['ID']['input']>;
  code?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<AccountType>;
  tenantId?: InputMaybe<Scalars['String']['input']>;
  tenant?: InputMaybe<TenantCreateOrUpdateInput>;
};

export type AccountsCreateOrUpdateManyInput = {
  data: Array<AccountCreateOrUpdateInput>;
};

export type ProfitAndLossRowsInsertManyInput = {
  data: Array<ProfitAndLossRowInsertInput>;
};

export type ProfitAndLossRowInsertInput = {
  date?: InputMaybe<Scalars['ISOString']['input']>;
  description: Scalars['String']['input'];
  amount: Scalars['Float']['input'];
  accountId?: InputMaybe<Scalars['ID']['input']>;
  account?: InputMaybe<AccountCreateOrUpdateInput>;
  tenantId?: InputMaybe<Scalars['ID']['input']>;
  tenant?: InputMaybe<TenantCreateOrUpdateInput>;
};

export type ProfitAndLossRowsUpdateManyInput = {
  data: Array<ProfitAndLossRowCreateOrUpdateInput>;
};

export type ProfitAndLossRowCreateOrUpdateInput = {
  id?: InputMaybe<Scalars['ID']['input']>;
  date?: InputMaybe<Scalars['ISOString']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  amount?: InputMaybe<Scalars['Float']['input']>;
  accountId?: InputMaybe<Scalars['ID']['input']>;
  account?: InputMaybe<AccountCreateOrUpdateInput>;
  tenantId?: InputMaybe<Scalars['ID']['input']>;
  tenant?: InputMaybe<TenantCreateOrUpdateInput>;
};

export type ProfitAndLossRowsCreateOrUpdateManyInput = {
  data: Array<ProfitAndLossRowCreateOrUpdateInput>;
};
