name: Deploy Admin UI Storybook to Netlify

on:
  push:
    paths:
      - "src/packages/admin-ui-components/**"
  pull_request:
    paths:
      - "src/packages/admin-ui-components/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: src
        run: pnpm install

      - name: Build vite-plugin-graphweaver
        working-directory: src
        run: pnpm turbo build --filter=vite-plugin-graphweaver --filter=@exogee/graphweaver-config --filter=@exogee/graphweaver-apollo-client

      - name: Build Storybook
        working-directory: src/packages/admin-ui-components
        run: pnpm -r build-storybook

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: nfp_SWbiG4kzTLagE5ScbGcvTFNM5L2ha34p7dc6
          NETLIFY_SITE_ID: e698cfda-37b2-46f6-9a98-6513b881f7c3
        with:
          args: deploy --dir=src/packages/admin-ui-components/storybook-static --prod
