name: CLI Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test-cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.29.1

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
          cache-dependency-path: src/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm i

      - name: Build CLI tool
        run: pnpm build

      - name: Create GW instance
        working-directory: src/packages/cli
        run: |
          pwd
          pnpm test:create

      - name: Change to GW instance and install
        working-directory: src/packages/cli/test
        run: |
          pwd
          npm i
      
      - name: Start GW instance
        working-directory: src/packages/cli/test
        timeout-minutes: 2
        run: |
          npm start &
          sleep 10 &&
          curl http://localhost:9000 &&
          killall node

        env:
          CI: true