name: Fuzzy Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auth-end-to-end-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions/cache@v4
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 9.15.3

      - uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: src/pnpm-lock.yaml

      - name: 🔥 Initialize MySQL
        run: sudo systemctl start mysql.service

      - name: Install dependencies
        run: pnpm i

      - name: Build CLI tool
        run: pnpm build

      - name: Import the REST with auth example
        working-directory: src/packages/end-to-end
        run: |
          pnpm import-auth
        env:
          CI: true
          DATABASE_HOST: 127.0.0.1
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: root

      - name: Start and Test Auth
        working-directory: src/packages/end-to-end
        timeout-minutes: 2
        run: |
          $(cd app && pnpm start) &
          sleep 5 &&
          pnpm test-fuzz &&
          killall node

        env:
          CI: true
          DATABASE_HOST: 127.0.0.1
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: root
          AUTH_PUBLIC_KEY_PEM_BASE64: ${{ secrets.AUTH_PUBLIC_KEY_PEM_BASE64 }}
          AUTH_PRIVATE_KEY_PEM_BASE64: ${{ secrets.AUTH_PRIVATE_KEY_PEM_BASE64 }}
          AUTH_BASE_URI: "http://localhost:9000"
          AUTH_WHITELIST_DOMAINS: "localhost"
          AUTH_MAGIC_LINK_RATE_LIMIT: "500"
