name: Standalone End-To-End Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  standalone-end-to-end-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
          ports:
          - 5432:5432
    env:
      CI: true
      DATABASE_HOST: localhost
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: gw

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PNPM cache
        uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.9

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: src/pnpm-lock.yaml
      
      - name: Install dependencies
        run: pnpm i
    
      - name: Store Playwright's version for caching purposes
        run: |
          PLAYWRIGHT_VERSION=$(pnpm ls --long @playwright/test | grep ^@playwright | sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache Playwright Browsers for a given Playwright version
        uses: actions/cache@v3
        id: cache-playwright-browsers    
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

      - name: Setup Playwright Using Cache If Available
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: pnpm playwright install --with-deps chromium

      - name: Run end-to-end tests
        run: |
          cd packages/end-to-end/scripts
          chmod +x test-standalone.sh
          ./test-standalone.sh
